/* 🚨 This file is generated by *GraphQL Codegen* 🚨 */

declare module "*/characters.graphql" {
	import { DocumentNode } from "graphql"
	const defaultDocument: DocumentNode
	export const Characters: DocumentNode

	export default defaultDocument
}
