/* 🚨 This file is generated by *GraphQL Codegen* 🚨 */
export type Maybe<T> = T | undefined
export type InputMaybe<T> = T | undefined
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] }
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & {
	[SubKey in K]?: Maybe<T[SubKey]>
}
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> }
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = {
	[_ in K]?: never
}
export type Incremental<T> =
	| T
	| { [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never }
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
	ID: { input: string; output: string }
	String: { input: string; output: string }
	Boolean: { input: boolean; output: boolean }
	Int: { input: number; output: number }
	Float: { input: number; output: number }
	Upload: { input: unknown; output: unknown }
}

export type CacheControlScope = "PRIVATE" | "PUBLIC"

export type Character = {
	created: Maybe<Scalars["String"]["output"]>
	episode: Array<Maybe<Episode>>
	gender: Maybe<Scalars["String"]["output"]>
	id: Maybe<Scalars["ID"]["output"]>
	image: Maybe<Scalars["String"]["output"]>
	location: Maybe<Location>
	name: Maybe<Scalars["String"]["output"]>
	origin: Maybe<Location>
	species: Maybe<Scalars["String"]["output"]>
	status: Maybe<Scalars["String"]["output"]>
	type: Maybe<Scalars["String"]["output"]>
}

export type Characters = {
	info: Maybe<Info>
	results: Maybe<Array<Maybe<Character>>>
}

export type Episode = {
	air_date: Maybe<Scalars["String"]["output"]>
	characters: Array<Maybe<Character>>
	created: Maybe<Scalars["String"]["output"]>
	episode: Maybe<Scalars["String"]["output"]>
	id: Maybe<Scalars["ID"]["output"]>
	name: Maybe<Scalars["String"]["output"]>
}

export type Episodes = {
	info: Maybe<Info>
	results: Maybe<Array<Maybe<Episode>>>
}

export type FilterCharacter = {
	gender: InputMaybe<Scalars["String"]["input"]>
	name: InputMaybe<Scalars["String"]["input"]>
	species: InputMaybe<Scalars["String"]["input"]>
	status: InputMaybe<Scalars["String"]["input"]>
	type: InputMaybe<Scalars["String"]["input"]>
}

export type FilterEpisode = {
	episode: InputMaybe<Scalars["String"]["input"]>
	name: InputMaybe<Scalars["String"]["input"]>
}

export type FilterLocation = {
	dimension: InputMaybe<Scalars["String"]["input"]>
	name: InputMaybe<Scalars["String"]["input"]>
	type: InputMaybe<Scalars["String"]["input"]>
}

export type Info = {
	count: Maybe<Scalars["Int"]["output"]>
	next: Maybe<Scalars["Int"]["output"]>
	pages: Maybe<Scalars["Int"]["output"]>
	prev: Maybe<Scalars["Int"]["output"]>
}

export type Location = {
	created: Maybe<Scalars["String"]["output"]>
	dimension: Maybe<Scalars["String"]["output"]>
	id: Maybe<Scalars["ID"]["output"]>
	name: Maybe<Scalars["String"]["output"]>
	residents: Array<Maybe<Character>>
	type: Maybe<Scalars["String"]["output"]>
}

export type Locations = {
	info: Maybe<Info>
	results: Maybe<Array<Maybe<Location>>>
}

export type Query = {
	character: Maybe<Character>
	characters: Maybe<Characters>
	charactersByIds: Maybe<Array<Maybe<Character>>>
	episode: Maybe<Episode>
	episodes: Maybe<Episodes>
	episodesByIds: Maybe<Array<Maybe<Episode>>>
	location: Maybe<Location>
	locations: Maybe<Locations>
	locationsByIds: Maybe<Array<Maybe<Location>>>
}

export type Query_CharacterArgs = {
	id: Scalars["ID"]["input"]
}

export type Query_CharactersArgs = {
	filter: InputMaybe<FilterCharacter>
	page: InputMaybe<Scalars["Int"]["input"]>
}

export type Query_CharactersByIdsArgs = {
	ids: Array<Scalars["ID"]["input"]>
}

export type Query_EpisodeArgs = {
	id: Scalars["ID"]["input"]
}

export type Query_EpisodesArgs = {
	filter: InputMaybe<FilterEpisode>
	page: InputMaybe<Scalars["Int"]["input"]>
}

export type Query_EpisodesByIdsArgs = {
	ids: Array<Scalars["ID"]["input"]>
}

export type Query_LocationArgs = {
	id: Scalars["ID"]["input"]
}

export type Query_LocationsArgs = {
	filter: InputMaybe<FilterLocation>
	page: InputMaybe<Scalars["Int"]["input"]>
}

export type Query_LocationsByIdsArgs = {
	ids: Array<Scalars["ID"]["input"]>
}

export type CharactersQueryVariables = Exact<{ [key: string]: never }>

export type CharactersQuery = {
	characters:
		| {
				info: { count: number | undefined; pages: number | undefined } | undefined
				results:
					| Array<
							| {
									id: string | undefined
									name: string | undefined
									status: string | undefined
									species: string | undefined
									image: string | undefined
							  }
							| undefined
					  >
					| undefined
		  }
		| undefined
}
