/** @type {import('@graphql-codegen/cli').CodegenConfig} */
export default {
	config: {
		// https://the-guild.dev/graphql/codegen/plugins/typescript/typescript
		skipTypename: true,
		addUnderscoreToArgsType: true,
		useTypeImports: true,
		avoidOptionals: true,
		disableDescriptions: true,
		enumsAsTypes: true,
		maybeValue: "T | undefined",
		defaultScalarType: "unknown",
		scalars: {
			Date: "Date",
			uuid: "string",
		},
		// https://the-guild.dev/graphql/codegen/plugins/other/add
		content: ["/* 🚨 This file is generated by *GraphQL Codegen* 🚨 */"],
	},
	generates: {
		"./src/app/services/spacex/generated-spacex.interface.ts": {
			schema: "https://spacex-production.up.railway.app",
			documents: "./src/app/services/spacex/queries/*.graphql",
			plugins: ["add", "typescript", "typescript-operations"],
		},
		"./src/app/services/spacex/generated-spacex.d.ts": {
			schema: "https://spacex-production.up.railway.app",
			documents: "./src/app/services/spacex/queries/*.graphql",
			plugins: ["add", "typescript-graphql-files-modules"],
		},
	},
}
