/** biome-ignore-all lint/style/noDefaultExport: default */

/** @type {import('@graphql-codegen/cli').CodegenConfig} */
export default {
	config: {
		// https://the-guild.dev/graphql/codegen/plugins/typescript/typescript
		skipTypename: true,
		addUnderscoreToArgsType: true,
		useTypeImports: true,
		avoidOptionals: true,
		disableDescriptions: true,
		enumsAsTypes: true,
		maybeValue: "T | undefined",
		defaultScalarType: "unknown",
		scalars: {
			Upload: "unknown",
		},
		// https://the-guild.dev/graphql/codegen/plugins/other/add
		content: ["/* 🚨 This file is generated by *GraphQL Codegen* 🚨 */"],
	},
	generates: {
		"./src/app/services/rick-morty/generated-rick-morty.interface.ts": {
			schema: "https://rickandmortyapi.com/graphql",
			documents: "./src/app/services/rick-morty/queries/*.graphql",
			plugins: ["add", "typescript", "typescript-operations"],
		},
		"./src/app/services/rick-morty/generated-rick-morty.d.ts": {
			schema: "https://rickandmortyapi.com/graphql",
			documents: "./src/app/services/rick-morty/queries/*.graphql",
			plugins: ["add", "typescript-graphql-files-modules"],
		},
	},
}
