/* 🚨 This file is generated by *GraphQL Codegen* 🚨 */

declare module "*/company.graphql" {
	import type { DocumentNode } from "graphql"
	const defaultDocument: DocumentNode
	export const Company: DocumentNode

	export default defaultDocument
}
